### ISSUE TITLE
Does not work if there is a space anywhere in the path

### ISSUE THREAD

**Issue by mprobber** [microlinkhq/youtube-dl-exec#186] opened 2024-03-01 07:42 UTC
Hi,
I'm working on a personal project and wish to use this library.  I am having issues because the path to the yt-dlp binary contains a space on my computer.  Spawn reads everything after the first space to the binary as an argument.

There is also no error printed when this happens, so it was difficult to figure out what exactly was happening.  I recommend that you change line 14 in index.js to simply

```javascript
if (!stdout) return isJSON(stdout) ? JSON.parse(stdout) : stdout;
```

because `stdout` was returning undefined for me.  This would have surfaced the error more easily.

**Comment by Kikobeats** [comment] 2024-03-01 09:01
Hello, Are you using Linux or Windows? Are you passing a custom path? Can you provide a reproduction?

**Comment by Kikobeats** [comment] 2024-03-02 19:27
Closing until a reproduciont or more information is provided

**Comment by mprobber** [comment] 2024-03-02 19:27
Hi, I am running Ubuntu in WSL, so Linux, but also sort of Windows.

This repository reproduces the error https://github.com/mprobber/youtube-dl-exec-bug-repro/tree/master

**Comment by mprobber** [comment] 2024-03-02 19:27
Please re-open :)

**Closed by Kikobeats** 2024-03-02 19:27 UTC

**Comment by Kikobeats** [comment] 2024-03-02 19:43
Since I don't have Linux I can't reproduce this, but CI machines are Linux too and tests are green.

Can you try to debug what's happening here? https://github.com/microlinkhq/youtube-dl-exec/blob/master/src/index.js#L18

**Comment by LagSlug** [comment] 2024-10-27 05:22
This is happening because the spawn command takes a space in the path and decides that's where the arguments list must start.

```
 stderr: undefined,
  stdout: undefined,
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\Name\\Documents\\FolderNameWith',
  path: 'C:\\Users\\Name\\Documents\\Rocks\\Building',
  spawnargs: [
    'Space\\app\\node_modules\\youtube-dl-exec\\bin\\yt-dlp.exe',
    'https://www.youtube.com/watch?v=########',
    '--update',
    '--dump-single-json',
    '--format',
    'best'
  ]

```

I've tried wrapping the path with quotes, but that hasn't resolved the issue.
