### ISSUE TITLE
youtube-dl-exec not working?

### ISSUE THREAD

**Issue by MattCrux** [microlinkhq/youtube-dl-exec#100] opened 2022-06-07 16:28 UTC
I ran the example code from the github snippet. It was working 3 days ago: it saved the video to the directory and logged the output in console, but now it no longer works? There's no video output for some reason

```
const youtubedl = require('youtube-dl-exec')

youtubedl('https://www.youtube.com/watch?v=6xKWiCMKKJg', {
  dumpSingleJson: true,
  noWarnings: true,
  noCallHome: true,
  noCheckCertificate: true,
  preferFreeFormats: true,
  youtubeSkipDashManifest: true,
  referer: 'https://www.youtube.com/watch?v=6xKWiCMKKJg'
}).then(output => console.log(output))
```

**Comment by Kikobeats** [comment] 2022-06-07 17:03
It's working; sorry but I have to close this issue since is not providing any kind of information to reproduce your issue

**Closed as completed by Kikobeats** 2022-06-07 17:03 UTC
Labels: wontfix
